# Generated by Django 5.0.1 on 2024-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awamain', '0002_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='awamain.category'),
        ),
    ]
